[06-09 13:07:36]: [INFO] Created column 'regdate' and set the current timestamp, 1591708056408, to all 0 rows
[06-09 13:07:36]: [INFO] SQLite Setup finished
[06-09 13:07:36]: [INFO] Hooked into LuckPerms!
[06-09 13:07:36]: [INFO] Hooked successfully into Multiverse-Core
[06-09 13:07:36]: [WARN] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[06-09 13:07:36]: [INFO] AuthMe 5.6.0-SNAPSHOT build n.2402 successfully enabled!
[06-09 13:07:40]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[06-09 13:07:40]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[06-09 13:07:40]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[06-09 13:07:40]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
[06-09 13:07:40]: java.io.FileNotFoundException: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[06-09 13:09:25]: [INFO] AuthMe 5.6.0-SNAPSHOT-b2402 disabled!
[06-09 13:09:26]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[06-09 13:09:27]: [WARN] Can't initialize the MySQL database: [CommunicationsException]: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[06-09 13:09:27]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:335)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2187)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:167)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:175)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:76)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:708)
	at net.minecraft.server.v1_15_R1.DedicatedServer.lambda$3(DedicatedServer.java:682)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.b(SourceFile:59)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:299)
	... 57 more

[06-09 13:09:27]: [WARN] Please check your database settings in the config.yml file!
[06-09 13:09:27]: [WARN] Could not create data source: [CommunicationsException]: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[06-09 13:09:27]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:335)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2187)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:167)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:175)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:76)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:708)
	at net.minecraft.server.v1_15_R1.DedicatedServer.lambda$3(DedicatedServer.java:682)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.b(SourceFile:59)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:299)
	... 57 more

[06-09 13:09:27]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[06-09 13:09:27]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:723)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:708)
	at net.minecraft.server.v1_15_R1.DedicatedServer.lambda$3(DedicatedServer.java:682)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.b(SourceFile:59)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918)
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911)
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:335)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2187)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:167)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:175)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:76)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 33 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:299)
	... 57 more

[06-09 13:09:27]: [INFO] AuthMe 5.6.0-SNAPSHOT-b2402 disabled!
[06-09 13:12:39]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[06-09 13:12:40]: [WARN] Can't initialize the MySQL database: [MySQLSyntaxErrorException]: Access denied for user 'minecraft'@'%' to database 'minecraft_auth'
[06-09 13:12:40]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'minecraft'@'%' to database 'minecraft_auth'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:167)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:175)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:76)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
	at java.lang.Thread.run(Thread.java:748)

[06-09 13:12:40]: [WARN] Please check your database settings in the config.yml file!
[06-09 13:12:40]: [WARN] Could not create data source: [MySQLSyntaxErrorException]: Access denied for user 'minecraft'@'%' to database 'minecraft_auth'
[06-09 13:12:40]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'minecraft'@'%' to database 'minecraft_auth'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:167)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:175)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:76)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
	at java.lang.Thread.run(Thread.java:748)

[06-09 13:12:40]: [WARN] Aborting initialization of AuthMe: [IllegalStateException]: Error during initialization of data source
[06-09 13:12:40]: java.lang.IllegalStateException: Error during initialization of data source
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:52)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:25)
	at fr.xephi.authme.libs.ch.jalu.injector.handlers.instantiation.ProviderHandler$InstantiationByProviderClass.instantiateWith(ProviderHandler.java:129)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolveContext(InjectorImpl.java:164)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.resolve(InjectorImpl.java:133)
	at fr.xephi.authme.libs.ch.jalu.injector.InjectorImpl.getSingleton(InjectorImpl.java:72)
	at fr.xephi.authme.AuthMe.instantiateServices(AuthMe.java:245)
	at fr.xephi.authme.AuthMe.initialize(AuthMe.java:221)
	at fr.xephi.authme.AuthMe.onEnable(AuthMe.java:145)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464)
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378)
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457)
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274)
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Access denied for user 'minecraft'@'%' to database 'minecraft_auth'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at fr.xephi.authme.libs.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	at fr.xephi.authme.libs.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at fr.xephi.authme.libs.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112)
	at fr.xephi.authme.datasource.MySQL.getConnection(MySQL.java:167)
	at fr.xephi.authme.datasource.MySQL.checkTablesAndColumns(MySQL.java:175)
	at fr.xephi.authme.datasource.MySQL.<init>(MySQL.java:76)
	at fr.xephi.authme.initialization.DataSourceProvider.createDataSource(DataSourceProvider.java:67)
	at fr.xephi.authme.initialization.DataSourceProvider.get(DataSourceProvider.java:49)
	... 17 more

[06-09 13:12:40]: [INFO] AuthMe 5.6.0-SNAPSHOT-b2402 disabled!
[06-09 13:17:06]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[06-09 13:17:06]: [INFO] Created column 'regdate' and set the current timestamp, 1591708626265, to all 0 rows
[06-09 13:17:06]: [INFO] MySQL setup finished
[06-09 13:17:06]: [INFO] Hooked into LuckPerms!
[06-09 13:17:06]: [INFO] Hooked successfully into Multiverse-Core
[06-09 13:17:06]: [WARN] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[06-09 13:17:06]: [INFO] AuthMe 5.6.0-SNAPSHOT build n.2402 successfully enabled!
[06-09 13:17:10]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[06-09 13:17:10]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[06-09 13:17:10]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[06-09 13:17:10]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
[06-09 13:17:10]: java.io.FileNotFoundException: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[06-09 13:17:36]: [FINE] ticklemynausea registered 192.168.88.250
[06-09 13:17:36]: [FINE] ticklemynausea logged in!
[06-09 16:56:01]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[06-09 16:56:01]: [INFO] MySQL setup finished
[06-09 16:56:01]: [INFO] Hooked into LuckPerms!
[06-09 16:56:01]: [INFO] Hooked successfully into Multiverse-Core
[06-09 16:56:01]: [WARN] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[06-09 16:56:01]: [INFO] AuthMe 5.6.0-SNAPSHOT build n.2402 successfully enabled!
[06-09 16:56:03]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[06-09 16:56:03]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[06-09 16:56:03]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[06-09 16:56:03]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
[06-09 16:56:03]: java.io.FileNotFoundException: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[06-09 16:57:41]: [FINE] ticklemynausea logged in!
[06-09 17:00:56]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[06-09 17:00:56]: [INFO] MySQL setup finished
[06-09 17:00:56]: [INFO] Hooked into LuckPerms!
[06-09 17:00:56]: [INFO] Hooked successfully into Multiverse-Core
[06-09 17:00:56]: [WARN] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[06-09 17:00:56]: [INFO] AuthMe 5.6.0-SNAPSHOT build n.2402 successfully enabled!
[06-09 17:00:58]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[06-09 17:00:58]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[06-09 17:00:58]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[06-09 17:00:58]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
[06-09 17:00:58]: java.io.FileNotFoundException: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[06-09 17:01:33]: [FINE] ticklemynausea logged in!
[06-09 17:01:52]: [INFO] AuthMe 5.6.0-SNAPSHOT-b2402 disabled!
[06-10 10:17:11]: [INFO] Connection arguments loaded, Hikari ConnectionPool ready!
[06-10 10:17:11]: [INFO] MySQL setup finished
[06-10 10:17:11]: [INFO] Hooked into LuckPerms!
[06-10 10:17:11]: [INFO] Hooked successfully into Multiverse-Core
[06-10 10:17:11]: [WARN] WARNING! The protectInventory feature requires ProtocolLib! Disabling it...
[06-10 10:17:11]: [INFO] AuthMe 5.6.0-SNAPSHOT build n.2402 successfully enabled!
[06-10 10:17:13]: [INFO] Downloading GEO IP database, because the old database is older than 30 days or doesn't exist
[06-10 10:17:13]: [WARN] No MaxMind credentials found in the configuration file! GeoIp protections will be disabled.
[06-10 10:17:13]: [INFO] There is no newer GEO IP database uploaded to MaxMind. Using the old one for now.
[06-10 10:17:13]: [WARN] Could not download GeoLiteAPI database [FileNotFoundException]: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
[06-10 10:17:13]: java.io.FileNotFoundException: plugins/AuthMe/GeoLite2-Country.mmdb (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at fr.xephi.authme.libs.com.maxmind.db.BufferHolder.<init>(BufferHolder.java:20)
	at fr.xephi.authme.libs.com.maxmind.db.Reader.<init>(Reader.java:121)
	at fr.xephi.authme.service.GeoIpService.startReading(GeoIpService.java:173)
	at fr.xephi.authme.service.GeoIpService.updateDatabase(GeoIpService.java:144)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81)
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

